#' @title Run CoNGA
#'
#' @description Runs CoNGA on data generated by Rdiscvr::CreateMergedTcrClonotypeFile
#' @param features_file textfile with list of most variable genes
#' @param tcr_datafile Merged TCR clonotype file
#' @param gex_datafile h5 file
#' @param organism 'human' or 'rhesus'
#' @param outfile_prefix prefix to output files
#' @param gex_datatype "10x_h5"
#' @param clones_file clones file generated by CoNGA
#' @param outfile_prefix_for_qc_plots prefix to qc output files
#'
#' @export

RunCoNGA <- function(features_file, tcr_datafile, gex_datafile, organism,
                      outfile_prefix, gex_datatype, clones_file, 
                      outfile_prefix_for_qc_plots) {
  dir <- system.file("scripts", package = "CellMembrane")
  setwd(dir)
  files <- list.files(dir, recursive = FALSE, full.names = FALSE)
  file <- files[files == 'run_CoNGA.py']
  str <- readr::read_file(file)
  script <- tempfile()
  readr::write_file(str, script)
  newstr <- paste0("run_CoNGA(features_file = '", features_file,
                   "',tcr_datafile = '", tcr_datafile, "', gex_datafile = '",
                   gex_datafile, "', organism = '", organism,
                   "', outfile_prefix = '", outfile_prefix,"', gex_datatype = '",
                   gex_datatype, "', clones_file = '", clones_file,
                   "', outfile_prefix_for_qc_plots = '", 
                   outfile_prefix_for_qc_plots,"')")
  readr::write_file(newstr, script, append = TRUE)
  system2(reticulate::py_exe(), script)
}


